#!/bin/bash
# should start SteamCatalog

# some things that run always

case "$1" in
  start)
    cd /var/www/SteamCatalog && bin/rails server -e production -b 127.0.0.1 -p 3000 -d
    ;;
  stop)
    kill $(cat /var/www/SteamCatalog/tmp/pids/server.pid)
    ;;
  *)
    echo "Usage: /etc/init.d/steamcatprod {start|stop}"
    exit 1
    ;;
esac

exit 0

